      PROGRAM addZ_pqr_pdbqt
      implicit real (a-h,o-z)
C
C
C     D. Suarez 
C
      parameter(maxatm=500000,maxres=200000)
C
C     PDBQT 
C
      dimension x1(maxatm),y1(maxatm),z1(maxatm)
      dimension q1(maxatm),rad1(maxatm),qdock1(maxatm)
      character*3  atype1(maxatm) 
      dimension nfa1(maxres),nla1(maxres)
      dimension Idatm1(maxatm),Idres1(maxres)
      character resnam1(maxres)*3
      character ta1(maxatm)*4
C
C     PQR
C
      dimension x0(maxatm),y0(maxatm),z0(maxatm)
      dimension q0(maxatm),rad0(maxatm)
      dimension nfa0(maxres),nla0(maxres)
      dimension Idatm0(maxatm),Idres0(maxres)
      character resnam0(maxres)*3
      character ta0(maxatm)*4
      dimension Idzatm0(maxatm)
C
      character*80 line 
      dimension i1match(maxatm)
      dimension i0match(maxatm)
C
      character finp0*256,finp1*256,fout*256,qopt*10
      character head*6 , ta_temp*4
      logical diffnat, EOF , keepQ
C
C    Beginning, Okay!  
C
      diffnat=.false.
      keepQ=.false.
      finp0=' '
      finp1=' '
      fout=' '
      qopt=' '
      CALL GETARG(1,finp0)
      CALL GETARG(2,finp1)
      CALL GETARG(3,fout)
      CALL GETARG(4,qopt)
      IF ((finp1 .eq.' ').or.(finp0.eq.' ').or.(fout.eq.' ')) THEN 
        print*, 'Usage: pqrpdbqt pqr pdbqtinp pdbqtout  [keep_charge]  '
        print*,'    pqr= PQR file generated by cpptraj' 
        print*,'    pdbqtout contains a reordering list'
        print*,'    If keep_charge is provided then '
        print*,'    PQR charges are not used. This is useful to '
        print*,'    print just the ordering list'
        STOP
      ENDIF
      if (( qopt .eq. 'keep_charge').or.( qopt .eq. 'KEEP_CHARGE')) 
     &   keepQ=.true.
C
C     Reading File PDBQT
C
      OPEN (10,file=finp1,status='unknown')
      CALL RDPDBQT (10,NAT1,NRES1,NFA1,NLA1,TA1,RESNAM1,
     &     IDATM1,IDRES1,X1,Y1,Z1,Q1,RAD1,QDOCK1,ATYPE1)
      CLOSE(10)
      qsum=0.0
      DO i=1,nat1
        qsum=qsum+qdock1(i)
      ENDDO
      WRITE(6,'(''Sum of charges in PDBQT1 input file ='',F8.2)') qsum

C
C     Reading PQR File 
C
      OPEN (10,file=finp0,status='unknown')
      CALL RDPQR (10,NAT0,NRES0,NZATM0,NFA0,NLA0,TA0,RESNAM0,
     &     IDATM0,IDRES0,IDZATM0,X0,Y0,Z0,Q0,RAD0)
      CLOSE(10)
      qsum=0.0
      DO i=1,nat0
        qsum=qsum+q0(i)
      ENDDO
      WRITE(6,'(''Sum of charges in PQR input file ='',F8.2)') qsum
C
      IF ( NAT1 .ne. NAT0 ) THEN 
         print*,'Number of atoms do not match !'
         print*,nat0,nat1
         print*,'We proceed anyway'
         diffnat=.true.
      ENDIF
C
      IF ( NRES1 .ne. NRES0 ) THEN 
         print*,'Number of residues do not match !',nres0,nres1
         print*,'We cannot proceed further '
         stop 
      ENDIF
C
C      Assigning PQR(Amber charges) to pdbqt 
C
       eps=0.05

       nmatch=0
       DO IAT0=1,NAT0
          I0MATCH(iat0)=0
       ENDDO
       DO IRES1=1,NRES1
       DO IAT1=NFA1(IRES1),NLA1(IRES1)
          I1MATCH(IAT1)=0
          IMIN=0
          RMIN=99999.
          DO IAT0=1,NAT0
             R= (x1(iat1)-x0(iat0))**2 + (y1(iat1)-y0(iat0))**2
     &          + (z1(iat1)-z0(iat0))**2            
             R=SQRT(R)
             IF ( R .lt. RMIN) THEN
                IMIN=IAT0
                RMIN=R
             ENDIF
          ENDDO
          IF ( RMIN .lt. eps ) THEN 
             nmatch=nmatch+1
             I1MATCH(IAT1)=IMIN
             I0MATCH(IMIN)=IAT1
c            WRITE(6,'('' PDBQT '',I4,A3,1X,A3,'' PQR '',I4,A3,
c    &       '' R= '',F8.3)')  
c    &       IDATM1(IAT1),TA1(IAT1),RESNAM1(IRES1),
c    &       IDATM0(IMIN),TA0(IMIN),RMIN
          ELSE
             I1MATCH(IAT1)=0
c            WRITE(6,'('' PDBQT '',I4,A3,1X,A3,'' NO MATCH '')') 
c    &       IDATM1(IAT1),TA1(IAT1),RESNAM1(IRES1)
          ENDIF
       ENDDO
       ENDDO 

       IF ( NMATCH .lt. NAT0 ) THEN
          DO IAT0=1,NAT0
             IF ( I0MATCH(iat0) .eq. 0 ) THEN
                 ta_temp=TA0(iat0)
                 IF (ta_temp(1:1) .ne. ' ') THEN
                     ita=1
                 ELSEIF ( ta_temp(2:2) .ne. ' ') THEN
                     ita=2
                 ELSEIF ( ta_temp(3:3) .ne. ' ') THEN
                     ita=3
                 ELSE
                     ita=4
                 ENDIF
                 IF (ta_temp(ita:ita) .ne. 'H') THEN
                    WRITE(6,'(''UNMATCHED PQR ATOM '',I4,1X,A4,
     &              '' IS NOT HYDROGEN: THIS IS AN ERROR'')')
     &               IAT0,ta_temp
                    STOP
                 ENDIF
                 IXMIN=0
                 IH=iat0
                 RMIN=999999.
                 DO I=1,NMATCH
                    ix=I1MATCH(I)
                    R= (x0(ix)-x0(ih))**2 
     &          + (y0(ix)-y0(ih))**2            
     &          + (z0(ix)-z0(ih))**2            
                    R=SQRT(R)
                    IF ( R .lt. RMIN) THEN 
                        IXMIN=IX   
                        RMIN=R
                    ENDIF
                 ENDDO
c                WRITE(6,'(''UNMATCHED PQR ATOM '',I4,1X,A4,
c    &              '' SEEMS BONDED TO'',I4,1X,A4,F8.3)')
c    &               ih,ta0(ih),ixmin,ta0(ixmin),rmin
                 Q0(IXMIN)=Q0(IXMIN)+Q0(IH)
             ENDIF
           ENDDO
       ENDIF
       IF ( .not. KEEPQ ) THEN 
             DO IAT1=1,NAT1
                  QDOCK1(IAT1)=Q0(I1MATCH(IAT1))
             ENDDO
       ENDIF
C
C     Relabelling Z-atoms 
C   
      DO I=1,NZATM0
         DO IAT0=1,NAT0
            IF ( IDATM0(IAT0) .eq. IDZATM0(I) ) THEN
               IAT1=I0MATCH(IAT0)
               IF ( IAT1 .gt. 0 ) THEN 
                     ATYPE1(IAT1)=' Z '
               ELSE
                 WRITE(6,'(''UNMATCHED PQR Z-ATOM '',I4,1X,A4)')
     &           IAT0,TA0(IAT0)
                 WRITE(6,'(''THIS IS AN ERROR'')')
                 STOP
              ENDIF
            ENDIF
         ENDDO
      ENDDO
C
C     Nullifying charges of Z ADCK TYPE ATOMS: 
C  
      IF ( NZATM0 .gt. 0 ) THEN 
C
      WRITE(6,'(I3,'' Z-atom IDs read from input PQR'')') NZATM0
      WRITE(6,'(''Z-atom PDBQT charges nullified and redistributed'')')
C
      NDZ=0
      qZ=0.0
      DO IRES=1,NRES1
         DO IAT=NFA1(IRES),NLA1(IRES)
            IF ( INDEX(ATYPE1(IAT),' Z ') .ne. 0 ) THEN
              NDZ=NDZ+1
              WRITE(6,'( A5,1X,I3,1X,A4 ,
     &        '' Z covalent atom -> charged nullified '')') 
     &        RESNAM1(IRES),IRES,TA1(IAT)
              qz=qz+QDOCK1(IAT)
              QDOCK1(IAT)=0.0
           ENDIF
         ENDDO
      ENDDO
C
C     Original CHARGE of Z ADCK atoms in PDBQT is redistributed 
C     to preserve charge integrity 
C
      IF ( NDZ .gt. 0 )  THEN
         qZ=qZ/FLOAT(NAT1-NDZ) 
         DO IAT=1,NAT1
            IF ( INDEX(ATYPE1(IAT),' Z ') .eq. 0 ) 
     &      QDOCK1(IAT)=QDOCK1(IAT)+qZ 
         ENDDO  
         IF ( NDZ .ne. NZATM ) 
     &   WRITE(6,'('' Only '',I3,'' matches found '')') NDZ
      ENDIF
C
      ENDIF
C
C      Print output
C
      OPEN (10,file=finp1,status='unknown')
      OPEN (12,file=fout,status='unknown')
      IAT=0
      DO WHILE (.not. EOF(LINE,10) ) 
         HEAD=LINE(1:6)
         IF ((HEAD .eq. 'ATOM  ') .or. (HEAD .eq. 'HETATM')) THEN
               iat=iat+1
               ires=iwhichRES(iat,nres1,nfa1,nla1) 
               write(12,'(''ATOM'',
     +         2X,I5,1X,A4,1X,A3,1X,I5,4X,3F8.3,2F6.2,F10.3,A3)')
     +         Idatm1(iat),ta1(iat),resnam1(ires),Idres1(ires),
     +         x1(iat),y1(iat),z1(iat),q1(iat),rad1(iat),qdock1(iat),
     +         atype1(iat)
         ELSE
             WRITE(12,'(A80)') LINE
         ENDIF
      ENDDO
C
      DO i=1,nmatch
         WRITE(12,'(''COMMENT PDBQT_PQR_MATCH  '',I4,1X,I4)') 
     &             I,I1MATCH(I)
      ENDDO
C
      CLOSE(10)
      CLOSE(12)
C
      STOP
C
      END
C
C
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C
      SUBROUTINE RDPDBQT (IUNIT,NUMATM,NUMRES,NFA,NLA,TA,RESNAM,
     &                  IDATM,IDRES,XR,YR,ZR,Q,RAD,QDOCK,ATYPE)
C     =============================================================
C
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
      implicit real  (a-h,o-z)
      parameter(maxatm=500000,maxres=200000)
C
C     All cards  ATOM or HETATM in IUNIT are
C     read to fill the coordinates and data for the protein
C
C     NOTE THAT THIS ROUTINE ASSUMES THAT BIG PDB FILES
C     ARE WELL WRITTEN, THAT IS, THAT RESIDUE NUMBER
C     IS WRITTEN WITH FORMAT I5
C
      integer iunit, numatm, numres
      dimension xr(*),yr(*),zr(*)
      dimension q(*),rad(*),qdock(*)
      character*3 atype(*)
      dimension nfa(*),nla(*),idres(*),idatm(*)
      character*4 ta(*)
      character*3 resnam(*) 
      character*80 line
C
      character head*4,tdum*3,tadum*4
C
      numatm=0
      numres=0
      iat=0
      ires=0
      idum0=0
      jres=0
C
      rewind(iunit)
 10   read(iunit,'(A4)',end=20,err=666) head
C
      IF (( head .eq. 'ATOM') .OR. 
     +         ( head .eq. 'HETA'))  THEN 

          backspace(iunit)
          iat=iat+1
          IF ( iat .gt. maxatm ) THEN 
               WRITE(6,'(''Reading Unit'',I3)') IUNIT  
               READ (IUNIT,'(A)') line
               WRITE(6,'(''Last line:'',/,A)') line   
               WRITE(6,'(''MAXATM='',I6)') maxatm 
               STOP '*** Too many atoms in PDB'
          ENDIF 
          tadum=''
          tdum=''
          read(iunit,'(6X,I5,1X,A4,1X,A3,1X,I5,4X,3F8.3,2F6.2,F10.3,A3)'
     &    ,err=666,end=666)
     & jat,tadum,tdum,jres,xr(iat),yr(iat),zr(iat),
     & q(iat),rad(iat),qdock(iat),atype(iat)
          Idatm(iat)=jat
C Checking prime issue
          l=0
          do i=1,4
            if ( tadum(i:i) .ne. '') l=l+1
          enddo
          if (tadum(1:1) .eq. '''' )  then
c             print*,'Problem tadum=',tadum 
              do i=1,l-1
                tadum(i:i)=tadum(i+1:i+1)
              enddo
              tadum(l:l)=''''
c             print*,'Fixed tadum=',tadum 
          endif
          ta(iat)=tadum
          IF ( idum0 .ne. jres) THEN
            ires=ires+1
            nfa(ires)=iat
            resnam(ires)=tdum
            idres(ires)=jres
            idum0=jres
          ENDIF
C
      ENDIF
C
      GOTO 10
C
 20   CONTINUE
C
      numatm=iat
      numres=ires
      DO ires=1,numres-1
        nla(ires)=nfa(ires+1)-1
      ENDDO
      nla(numres)=numatm
C
      IF (NUMATM .eq. 0) THEN 
        WRITE(6,*) 'Zero Atoms in PDB file UNIT= ',Iunit
        STOP
      ENDIF
C
      RETURN
C
 666  WRITE(6,*) 'PROBLEMS READING PDB FILE IN UNIT=', Iunit
      STOP
      END
C
C
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C
      SUBROUTINE RDPQR (IUNIT,NUMATM,NUMRES,NZATM,NFA,NLA,TA,RESNAM,
     &                  IDATM,IDRES,IDZATM,XR,YR,ZR,Q,RAD)
C     =============================================================
C
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
      implicit real  (a-h,o-z)
      parameter(maxatm=500000,maxres=200000)
C
C     All cards  ATOM or HETATM in IUNIT are
C     read to fill the coordinates and data for the protein
C
C     NOTE THAT THIS ROUTINE ASSUMES THAT BIG PDB FILES
C     ARE WELL WRITTEN, THAT IS, THAT RESIDUE NUMBER
C     IS WRITTEN WITH FORMAT I5
C
      integer iunit, numatm, numres
      dimension xr(*),yr(*),zr(*)
      dimension q(*),rad(*)
      dimension nfa(*),nla(*),idres(*),idatm(*)
      dimension idzatm(*)
      dimension indx(100),rx(100)
      character*4 ta(*)
      character*3 resnam(*) 
      character*80 line
C
      character head*4,tdum*3
C
      numatm=0
      numres=0
      iat=0
      ires=0
      idum0=0
      jres=0
      nzatm=0
C
      rewind(iunit)
 10   read(iunit,'(A4)',end=20,err=666) head
C
      IF ( head .eq. 'ZATM' ) THEN
          backspace(iunit)
          read(iunit,'(A80)') line
          CALL RDLINEA(line,indx,ni,rx,nr,nx,1)
          DO I=1,NI
             idzatm(NZATM+I)=indx(I)
          ENDDO
          NZATM=NZATM+NI

      ELSEIF (( head .eq. 'ATOM') .OR. 
     +         ( head .eq. 'HETA'))  THEN 

          backspace(iunit)
          iat=iat+1
          IF ( iat .gt. maxatm ) THEN 
               WRITE(6,'(''Reading Unit'',I3)') IUNIT  
               READ (IUNIT,'(A)') line
               WRITE(6,'(''Last line:'',/,A)') line   
               WRITE(6,'(''MAXATM='',I6)') maxatm 
               STOP '*** Too many atoms in PDB'
          ENDIF 
          read(iunit,'(6X,I5,1X,A4,1X,A3,1X,I5,4X,3F8.3,2F8.4)'
     &    ,err=666,end=666)
     & jat,ta(iat),tdum,jres,xr(iat),yr(iat),zr(iat),q(iat),rad(iat)
          Idatm(iat)=jat
          IF ( idum0 .ne. jres) THEN
            ires=ires+1
            nfa(ires)=iat
            resnam(ires)=tdum
            idres(ires)=jres
            idum0=jres
          ENDIF
C
      ENDIF
C
      GOTO 10
C
 20   CONTINUE
C
      numatm=iat
      numres=ires
      DO ires=1,numres-1
        nla(ires)=nfa(ires+1)-1
      ENDDO
      nla(numres)=numatm
C
      IF (NUMATM .eq. 0) THEN 
        WRITE(6,*) 'Zero Atoms in PDB file UNIT= ',Iunit
        STOP
      ENDIF
C
      RETURN
C
 666  WRITE(6,*) 'PROBLEMS READING PDB FILE IN UNIT=', Iunit
      STOP
      END
C
C     Esta rutina no esta igual en todos los FORTRAN
C     Si hay un fallo en algun codigo en lectura de numeros
C     actualizarla por esta
C
      SUBROUTINE RDLINEA(var,INDX,NI,RX,NR,NX,IOP)
      implicit real (a-h,o-z)
C
C     Esta subrutina, asi en castellano de vez en cuando
C     esta muy guapo, intentara leer indices numericos
C     contenidos en un variable alfanumerica
C     Es un poco chapuza, pero esperamos que efectiva !
C
C     Si IOP = 1 Lectura de numeros enteros
C     Si IOP = 2 Lectura de numeros reales
C     Si IOP = 3 Lectura de numeros enteros y reales
C
C     Si IOP=-1 en la salida....chungo !
C
C     Lectura ordenada
C
      character var*(*)
      character*1 ca,cc,cb
      logical NUMI,NUMR
      dimension INDX(*),RX(*)
      dimension ibra(50),jbra(50)
C
      NUMI=.false.
      IF (( IOP .eq. 1) .or. (IOP .eq. 3)) NUMI=.true.
      NUMR=.false.
      IF (( IOP .eq. 2) .or. (IOP .eq. 3)) NUMR=.true.
C
      L=LEN(var)
      IF ( L .eq. 0 ) THEN
          IOP=-1
          RETURN
      ENDIF
      nbra=0
      nleft=0
      nright=0
      DO I=1,L
        ja=I-1
        jb=I
        jc=I+1
C
        IF (ja .gt. 0 ) THEN 
           ca=VAR(ja:ja)
        ELSE
           ca=' '
        ENDIF
        cb=VAR(jb:jb)
        IF (jc .lt.  L ) THEN 
           cc=VAR(jc:jc)
        ELSE
           cc=' '
        ENDIF
C
        IF (((( cb .eq. '-') .or. ( cb  .eq. '.')  .or.
     +  ((cb .ge. '0') .and. (cb .le. '9')))) 
     +  .and. (ca .eq. ' ') .and. 
C
     +  ( ((cc .ge. '0') .and. (cc .le.'9')) .or. 
     +    ((cc .eq. '.') .or.  (cc .eq.' ')) ) ) THEN 
           nleft=nleft+1
           ibra(nleft)=I
        ENDIF
C
        IF ( ( ((ca .ge. '0') .and. (ca .le. '9')) .or.
     +          (ca .eq. '-')  .or. (ca .eq. '.')  .or. 
     +          (ca .eq. ' ') )  .and. 
     +          ((cb .ge. '0') .and. (cb .le. '9')) 
     +          .and. ( cc .eq. ' ') )  THEN
           nright=nright+1
           jbra(nright)=I
        ENDIF
      ENDDO
C
C
      IF ( nright .ne. nleft) THEN
        print*, nright,nleft
        write(6,'(2X,''Failing while reading numbers from '',//,A256)')
     +  var      
        IOP=-1
        RETURN
      ENDIF
C
      nbra=nleft
      NX=0
      NR=0
      NI=0
C
      DO I=1,nbra
        ipos=ibra(I)
        jpos=jbra(I)
        IF ((INDEX(var(ipos:jpos),'.') .ne. 0 ) .and. (NUMR)) THEN
           NX=NX+1
           NR=NR+1
           READ(var(ipos:jpos),*,err=666,end=666) RX(NR)
        ELSE IF ( NUMI) THEN
           NX=NX+1
           NI=NI+1
           READ(var(ipos:jpos),*,err=666,end=666) INDX(NI)
        ENDIF
      ENDDO
C
      RETURN
 666  IOP=-1
      RETURN
C
      END 
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
      function iwhichRES (IAT,NRES,NFA,NLA)
C     =====================================      
C
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C
      implicit real*8 (a-h,o-z)
      dimension NFA(*),NLA(*)
      DO IRES=1,NRES
         IF (( NFA(IRES) .le. IAT) .and. (IAT .le. NLA(IRES))) THEN
            iwhichRES=IRES
            RETURN
         ENDIF
      ENDDO
      iwhichRES=0
      RETURN
      END
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
      LOGICAL function EOF (LINE,IUNIT)
C     =================================      
C
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C
      implicit real*8 (a-h,o-z)
      character*(*)  LINE
      READ (IUNIT,'(a)',ERR=100,END=100)  LINE
      EOF = .false.
      RETURN
 100  CONTINUE
      EOF = .true.
      LINE=' '
      RETURN
      END
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C                                                                       
      SUBROUTINE UCASE (STRNG)                                          
C    ==========================                                         
C                                                                       
C"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C     CONVERTS LOWER CASE CHARACTERS TO UPPER CASE                       
C                                                                       
      CHARACTER*(*) STRNG                                               
C                                                                       
C      write(7,'(A)') STRNG                                             
C                                                                       
      DO 10 I = 1,LEN(STRNG)                                            
         IF ( ( STRNG(I:I).GE. 'a' )  .AND.                             
     +        ( STRNG(I:I) .LE. 'z' ) )                                 
     +   STRNG(I:I) = CHAR(ICHAR(STRNG(I:I)) + ICHAR('A') - ICHAR('a')) 
 10   CONTINUE                                                          
      RETURN                                                            
      END                                                               
C
