#!/bin/bash 

#
if [ -z "$APTAMD" ]; then echo "APTAMD variable is not defined!" ; exit; fi
source $APTAMD/ENV/aptamd_env.sh

#
# This is the APTAMD script for carrying out NMODE calculations 
#
# Usage:
#
# bash calc_nmode LIST
#
# where LIST is a file containing the list of snapshot PDBs 
# For example,
#
#    snap_0001.pdb
#    snap_0002.pdb
#    snap_0003.pdb
#    snap_0003.pdb
#    ....
#
# All the parameters and settings needed to carry out the calculations
# must be specified in ENV variables. See "USER SPECIFICATION OF CONTROL VARIABLES" below.
#
# On output, calc_energy_analyses.sh produces for every snapshot several gzipped *.out files 
# generated by SANDER. For example, if CMPLX_MASK, HOST_MASK and LIG_MASK are given, 
# there are 5 files for each PDB snapshot:
#
#   snap_0001.out1     ...(MM minimization output file for complex)
#   snap_0001.nmode1   ...(NMODE output file for complex )
#   ........
#  ....  
#  The Information contained in the *.out[1-5] files must be processed usig the "do_energy_analyses.sh" 
#  and "do_stat.sh" scripts 
#

#Working directory 
export WORKDIR=$PWD

################ BEGINNING OF USER SPECIFICATION OF CONTROL VARIABLES #######################
#
# IT MAY BE POSSIBLE TO PREPAREATE THE INPUT PDB BY USINIG A CUSTOM SCRIPT DEFINED BY
# THE PREPARE_SNAP variable
#
# PREPARE_SNAP="DUMMY_PREPARE" 
#
# NOTE THAT IN CASE OF PREPAREATING THE SNAP BOTH THE RESIDUE NUMBERING AND THE
# REFERENCE TOPOLOGY MUST BE IN CONSONANCE WITH THE PREPAREATED SYSTEM
#
# MASK DEFINITION OF CMPLEX and FRAG SUBSYTEMS....
declare -a FRAG_MASK=""
declare -a WAT_FRAG_MASK=""
declare -a NWAT_FRAG=""

CMPLX_MASK="DUMMY_CMPLX_MASK"

# Leave NFRAG="0" if no fragments are defined
NFRAG="DUMMY_NFRAG" 
FRAG_MASK[1]="DUMMY_FRAG_01"
FRAG_MASK[2]="DUMMY_FRAG_02"
FRAG_MASK[3]="DUMMY_FRAG_03"
FRAG_MASK[4]="DUMMY_FRAG_04"
FRAG_MASK[5]="DUMMY_FRAG_05"
FRAG_MASK[6]="DUMMY_FRAG_06"
FRAG_MASK[7]="DUMMY_FRAG_07"
FRAG_MASK[8]="DUMMY_FRAG_08"
FRAG_MASK[9]="DUMMY_FRAG_09"
FRAG_MASK[10]="DUMMY_FRAG_10"
FRAG_MASK[11]="DUMMY_FRAG_11"
FRAG_MASK[12]="DUMMY_FRAG_12"
FRAG_MASK[13]="DUMMY_FRAG_13"
FRAG_MASK[14]="DUMMY_FRAG_14"
FRAG_MASK[15]="DUMMY_FRAG_15"
FRAG_MASK[16]="DUMMY_FRAG_16"
FRAG_MASK[17]="DUMMY_FRAG_17"
FRAG_MASK[18]="DUMMY_FRAG_18"
FRAG_MASK[19]="DUMMY_FRAG_19"
FRAG_MASK[20]="DUMMY_FRAG_20"

# WATERS to be included in FRAGMENT definitions
# NWAT_FRAG molecules around WAT_FRAG_MASK atoms are
# selected using the closestwaters tool in cpptraj
# If is possible to define several sites per fragment separated by semicolons.
# For example WAT_FRAG_MASK[1]=":1@NA ; :3@OG" 
#             NWAT_FRAG[1]=" 2  ;  4 " 
# WARNING: Residue numbering of CMPLX ! 

WAT_FRAG_MASK[1]="DUMMY_WAT_FRAG_01"
WAT_FRAG_MASK[2]="DUMMY_WAT_FRAG_02"
WAT_FRAG_MASK[3]="DUMMY_WAT_FRAG_03"
WAT_FRAG_MASK[4]="DUMMY_WAT_FRAG_04"
WAT_FRAG_MASK[5]="DUMMY_WAT_FRAG_05"
WAT_FRAG_MASK[6]="DUMMY_WAT_FRAG_06"
WAT_FRAG_MASK[7]="DUMMY_WAT_FRAG_07"
WAT_FRAG_MASK[8]="DUMMY_WAT_FRAG_08"
WAT_FRAG_MASK[9]="DUMMY_WAT_FRAG_09"
WAT_FRAG_MASK[10]="DUMMY_WAT_FRAG_10"
WAT_FRAG_MASK[11]="DUMMY_WAT_FRAG_11"
WAT_FRAG_MASK[12]="DUMMY_WAT_FRAG_12"
WAT_FRAG_MASK[13]="DUMMY_WAT_FRAG_13"
WAT_FRAG_MASK[14]="DUMMY_WAT_FRAG_14"
WAT_FRAG_MASK[15]="DUMMY_WAT_FRAG_15"
WAT_FRAG_MASK[16]="DUMMY_WAT_FRAG_16"
WAT_FRAG_MASK[17]="DUMMY_WAT_FRAG_17"
WAT_FRAG_MASK[18]="DUMMY_WAT_FRAG_18"
WAT_FRAG_MASK[19]="DUMMY_WAT_FRAG_19"
WAT_FRAG_MASK[20]="DUMMY_WAT_FRAG_20"

NWAT_FRAG[1]="DUMMY_NWAT_FRAG_01"
NWAT_FRAG[2]="DUMMY_NWAT_FRAG_02"
NWAT_FRAG[3]="DUMMY_NWAT_FRAG_03"
NWAT_FRAG[4]="DUMMY_NWAT_FRAG_04"
NWAT_FRAG[5]="DUMMY_NWAT_FRAG_05"
NWAT_FRAG[6]="DUMMY_NWAT_FRAG_06"
NWAT_FRAG[7]="DUMMY_NWAT_FRAG_07"
NWAT_FRAG[8]="DUMMY_NWAT_FRAG_08"
NWAT_FRAG[9]="DUMMY_NWAT_FRAG_09"
NWAT_FRAG[10]="DUMMY_NWAT_FRAG_10"
NWAT_FRAG[11]="DUMMY_NWAT_FRAG_11"
NWAT_FRAG[12]="DUMMY_NWAT_FRAG_12"
NWAT_FRAG[13]="DUMMY_NWAT_FRAG_13"
NWAT_FRAG[14]="DUMMY_NWAT_FRAG_14"
NWAT_FRAG[15]="DUMMY_NWAT_FRAG_15"
NWAT_FRAG[16]="DUMMY_NWAT_FRAG_16"
NWAT_FRAG[17]="DUMMY_NWAT_FRAG_17"
NWAT_FRAG[18]="DUMMY_NWAT_FRAG_18"
NWAT_FRAG[19]="DUMMY_NWAT_FRAG_19"
NWAT_FRAG[20]="DUMMY_NWAT_FRAG_20"

# WATER PEEL 
DO_PEEL="DUMMY_DO_PEEL"
PEEL="DUMMY_PEEL"

# REFERENCE TOPOLOGY FILE (must contain more water molecules than any snapshot)
# WE USE CPPTRAJ COMMANDS TO STRIP OFF THE REFERENCE TOPOLOGY FILE AND GET
# THE COORDINATES FOR ANALYSES
#
REFTOP="DUMMY_TOPOLOGY"

# SNAPSHOTS DIRECTORY: contains the gzipped PDB files generated
# by fullcontact that are to be processed
SNAP="DUMMY_SNAPSHOTS"

# The list of input PDB files (without the .gz extension)
# is read as an argument for the script 
files=$1

########################## END OF USER-SPECIFICATION OF CONTROL VARIABLES ###################33
# Programs being used    
#
# AMBER
SANDER="$AMBERHOME/bin/sander"
NMODE="$APTAMD/AUXTOOLS/nmode"
CPPTRAJ="$AMBERHOME/bin/cpptraj"
PARMED="$AMBERHOME/bin/parmed -n"
AMBMASK="$AMBERHOME/bin/ambmask"

# Auxiliary programs (in house; other tools could be used)
PDBCRD="$APTAMD/AUXTOOLS/pdbcrd"
REORDER="$APTAMD/AUXTOOLS/reorder"
#  NCDUMP converts netCDF file to text format. NETCDF library is required (usually bundled with AMBER).
NCDUMP=$(which  ncdump| grep -v alias)
if [ -z "$NCDUMP" ]; then echo 'ncudmp seems to be not available, but needed!';  DO_EXIT=1; fi
NCDUMP="${NCDUMP} -p 9,18"


# TEMP Directories
if [ ! -n "$PBS_ENVIRONMENT" ] ; then
   SCRATCH=/scratch
fi
TT=$(date +%N)
TMPDIR=${SCRATCH}/TMPDIR_${TT} 

# All work is done in a temporal directory
mkdir $TMPDIR
cd $TMPDIR

# SANDER input for XMIN optimization 
echo 'Minimization  ' > sander_min.inp
echo '&cntrl  ' >> sander_min.inp
#echo ' imin=1, maxcyc=50000,  ntmin=3, drms=0.000000001 ' >> sander_min.inp
echo ' imin=1, maxcyc=5000,  ntmin=3, drms=0.0000001 ' >> sander_min.inp
echo ' ntb=0, ntf=1, ntc=1, ntpr=50,   ntxo=2, ' >> sander_min.inp
echo ' cut=999., nsnb=50000,  igb=0, ' >> sander_min.inp
echo ' ibelly=1, bellymask=DUMMY_MASK, ' >> sander_min.inp
echo ' / ' >> sander_min.inp
echo ' &lmod ' >> sander_min.inp
echo "  xmin_verbosity=1, xmin_method='TNCG',  " >> sander_min.inp
echo ' / ' >> sander_min.inp

# Input para NMODE 
echo 'Frequencies   ' > nmode.inp
echo '&data ' >> nmode.inp
echo '    ntrun = 1, cut=999.0, ntx=2, ' >> nmode.inp
echo '    drms = 100.0 ,  ilevel=1,' >> nmode.inp
echo '    scnb=2.0, scee=1.2, dielc=1.0, idiel=1 ' >> nmode.inp
echo '    ismem=1,  nvect=0,  ' >> nmode.inp 
echo '    ibelly=1, ' >> nmode.inp
echo '&end '>> nmode.inp

################################################################################
# We discount waters and counterions from the total number of residues
# in REFTOP  in order to find the number of "cmplxein" residues (i.e., non-solvent) 

sed '1,/FLAG RESIDUE_LABEL/d' $REFTOP | sed '/FLAG/,$d' > RESLAB.dat
MAXWAT=$(grep 'WAT\|HOH' RESLAB.dat  | tr " \t" "\n" | grep -c 'WAT\|HOH' )
MAXNA=$(grep 'Na+' RESLAB.dat  | tr " \t" "\n" | grep -c 'Na+')
MAXCL=$(grep 'Cl-' RESLAB.dat | tr " \t" "\n" | grep -c 'Cl-')
POINTERS=($(grep 'FLAG POINTERS' -A 4 $REFTOP |tail -3)) 
MAXRES_REFTOP=${POINTERS[11]} 

let " NRES = $MAXRES_REFTOP - $MAXWAT - $MAXNA - $MAXCL " 

echo " $REFTOP has $NRES non-solvent resdidues, $MAXWAT waters, $MAXNA Na+ and $MAXCL Cl-" 

#REF topology is stripped from counterions and box information
$CPPTRAJ $REFTOP <<EOF
parmstrip :Na+,Cl-
parmbox nobox
parmwrite out REF.top.parm7
go
EOF
mv REF.top.parm7 REF.top 
REFTOP="./REF.top"

#=======================================================================================
# Big loop over input PDB files 
#=======================================================================================

N_SELECTED_WATERS=0
for  i  in $(cat $WORKDIR/$files)
do

#Cleaning up
rm -f  *.crd *.rst *.pqr *.pdb 
rm -f temp.*
rm -f cmplxwat.top 

# The following IF can be useful when resubmitting unfinished jobs
# so that only those PDB files for which no output is already available
# will be processed

if [ ! -e $WORKDIR/${i/.pdb/.out_min.gz} ] 
then 

# Uncompressing input PDB file
zcat  $SNAP/$i   >  $i

# PREPAREATE task here 
if [ "$PREPARE_SNAP" ]
then 
  echo "Preparing snapshot"
  bash $PREPARE_SNAP  $i
fi
mv $i temp.pdb 

#  Reordering 
sed -i 's/ W.. / WAT /' temp.pdb
$REORDER  < temp.pdb > temp2.pdb ; mv temp2.pdb temp.pdb
NWAT=$(grep -c 'O   WAT' temp.pdb)

# Peeling 
if [ "${DO_PEEL}" == "YES" ]  && [ $MAXWAT -gt $NWAT ]
then
     echo "Performing a peeling operation PEEL=$PEEL"
     # Preparing topology file for peeling 
     let " ARES = $NRES + $NWAT +  1 "
     let " BRES = $NRES + $MAXWAT "
     $PARMED  $REFTOP <<EOF
strip :${ARES}-${BRES}
parmout cmplxwat0.top 
go
EOF
    $CPPTRAJ cmplxwat0.top <<EOF
trajin  temp.pdb
watershell !:WAT,Na+,Cl-  lower ${PEEL}  upper  ${PEEL}  out temp.iswat
go 
EOF
   NWAT_IN=$(grep -v '#' temp.iswat | awk '{print $2}')
   $CPPTRAJ cmplxwat0.top <<EOF
trajin  temp.pdb
trajout temp_peeled.pdb pdb vdw include_ep
closest ${NWAT_IN} !:WAT,Na+,Cl- solventmask :WAT@O,Na+,Cl- 
go
EOF
   mv -f temp_peeled.pdb temp.pdb
   rm -f cmplxwat0.top
   unset NWAT ARES BRES NWAT_IN
fi

# Separate waters and cmplx 
grep WAT temp.pdb | grep 'ATOM '  >  wat.pdb
grep -v WAT temp.pdb > cmplx.pdb 
mv temp.pdb cmplxwat.pdb
NWAT=$(grep -c 'O   WAT' wat.pdb) 

# Preparing TOPOLOGY files
if [ "$MAXWAT" -gt "0" ] && [ "$NWAT" -gt "0" ] && [ "$MAXWAT" -gt "$NWAT" ]
then

let " ARES = $NRES + $NWAT +  1 "
let " BRES = $NRES + $MAXWAT "
$CPPTRAJ $REFTOP <<EOF
parmstrip :${ARES}-${BRES}
parmbox nobox
parmwrite out cmplxwat.top.parm7 
go
EOF
mv cmplxwat.top.parm7 cmplxwat.top

else

cp  $REFTOP cmplxwat.top 

fi

#Selecting fragment waters
declare -a NEW_FRAG_MASK=""
SELECTED_WATER=""
N_SELECTED_WATERS=0

let " TOTAL_RES = $NRES + $MAXWAT "

# Checking number of MOL fragments
$CPPTRAJ cmplxwat.top << EOF
trajin   cmplxwat.pdb 
trajout  cmplx.pdb include_ep 
strip  :WAT
go
EOF
NMOL=$(grep -c 'TER' cmplx.pdb)

# There may be repeated waters
declare -a IDWAT_CHECK=""
for ((ires=0;ires<=TOTAL_RES;ires++));do IDWAT_CHECK["$ires"]=0; done

for ((ifrag=1;ifrag<=NFRAG;ifrag++))
do

   declare -a NWFR=""
   declare -a MASK_FR=""
   declare -a QM_MASK_FR=""
   NWFR=($(echo ${NWAT_FRAG["$ifrag"]} | sed 's/;/  /g'))
   MASK_FR=($(echo ${WAT_FRAG_MASK["$ifrag"]} | sed 's/;/  /g'))  
   NSITE_NW=${#NWFR[@]}  
   NSITE_MASK=${#MASK_FR[@]}  

   echo " NWFR=${NWFR[*]}  MASK=${MASK_FR[*]}  NSITE_NW=${NSITE_NW} NSITE_MASK=${NSITE_MASK}"

   if [ "$NSITE_NW" -gt 0 ] &&  [ ${NWFR[0]} -gt 0 ]
   then

   if [ ${NSITE_NW} -ne ${NSITE_MASK} ]; then echo "Inconsistent definitions of NWFR, MASK, NSITE_NW, NSITE_MASK "; exit; fi

   DUMMY_WAT_MASK=""
   for ((ISITE=0;ISITE<=NSITE_NW-1;ISITE++))
   do

       NWFR_site=${NWFR["$ISITE"]}
       MASK_site=${MASK_FR["$ISITE"]}
       let "NWFR_get = 8 * $NWFR_site"
     
$CPPTRAJ cmplxwat.top << EOF
trajin cmplxwat.pdb 
closest $NWFR_get $MASK_site closestout temp.frwat
go
EOF

       declare -a DUMMY_WAT_IN_FRAG=""
       DUMMY_WAT_IN_FRAG=($(grep -v '#' temp.frwat | awk -v nres=$NRES -v nmol=$NMOL  '{print $2 + nres - nmol}'))
       echo "${DUMMY_WAT_IN_FRAG[*]}"
       
       for ((iwat=1;iwat<=NWFR_site;iwat++))
       do
         let " jwat = $iwat - 1"
         kwat=${DUMMY_WAT_IN_FRAG["$jwat"]}
 
#  For consistency, the same number of water molecules
#  should be picked up. We try to catch a second shell water
         if [ ${IDWAT_CHECK["$kwat"]} -eq 1 ]
         then
            for ((iwat_B=1;iwat_B<=7*NWFR_site;iwat_B++))
            do
                 let " jwat_B =  $NWFR_site + $iwat_B - 1"
                 kwat_B=${DUMMY_WAT_IN_FRAG["$jwat_B"]}
                 if [ ${IDWAT_CHECK["$kwat_B"]} -eq 0 ]
                 then
                     kwat=$kwat_B
                     break
                 fi
            done
         fi
   
         if [ ${IDWAT_CHECK["$kwat"]} -eq 0 ]
         then  
            DUMMY_WAT_MASK=${DUMMY_WAT_MASK}","${kwat}
            SELECTED_WATER=${SELECTED_WATER}","${kwat}
            let " N_SELECTED_WATERS= $N_SELECTED_WATERS + 1 "
            IDWAT_CHECK["$kwat"]="1"
         fi

       done
       MASK=${FRAG_MASK["$ifrag"]}
       NEW_FRAG_MASK["$ifrag"]="${DUMMY_WAT_MASK}" 

   done 

  else
    MASK=${FRAG_MASK["$ifrag"]}
    NEW_FRAG_MASK["$ifrag"]=${MASK} 
  fi

done

# Reordering selected waters
if [ ${N_SELECTED_WATERS} -gt 0 ]
then
   rm -f active.pdb frozen.pdb selected.pdb
   $PDBCRD  < cmplxwat.pdb > cmplxwat.crd

$CPPTRAJ  cmplxwat.top <<EOF
trajin cmplxwat.crd
trajout selected.pdb pdb include_ep
strip  !${CMPLX_MASK}${SELECTED_WATER}
go
EOF

$CPPTRAJ  cmplxwat.top <<EOF
trajin cmplxwat.crd
trajout frozen.pdb pdb  include_ep
strip  ${CMPLX_MASK}${SELECTED_WATER}
go
EOF

$CPPTRAJ  cmplxwat.top <<EOF
trajin cmplxwat.crd
trajout active.pdb pdb  include_ep
strip  !${CMPLX_MASK}
go
EOF

   iwat=${NRES}
   nwat_tot=0
   for ((ifrag=1;ifrag<=NFRAG;ifrag++)) 
   do

      declare -a NWFR=""
      NWFR=($(echo ${NWAT_FRAG["$ifrag"]} | sed 's/;/  /g'))
      NSITE_NW=${#NWFR[@]}
      if [ "$NSITE_NW" -gt 0 ] &&  [ ${NWFR[0]} -gt 0 ]
      then

      rm -f temp_frag_wat.pdb

$CPPTRAJ  cmplxwat.top <<EOF
trajin cmplxwat.crd
trajout temp_frag_wat.pdb pdb  include_ep
strip !:${NEW_FRAG_MASK["$ifrag"]}
go
EOF
     nwat_in_fr=$(grep 'ATOM ' temp_frag_wat.pdb | grep -c 'O   WAT' )
     let "iwat=${iwat}+1"
     let "jwat=${iwat}+${nwat_in_fr}-1" 
     let "nwat_tot=${nwat_tot}+${nwat_in_fr}"

     cat temp_frag_wat.pdb >> active.pdb   
     MASK=${FRAG_MASK["$ifrag"]}
     NEW_FRAG_MASK["$ifrag"]="${MASK},${iwat}-${jwat}"
     iwat=$jwat

     fi

   done
  
   let "iwat=${NRES}+1"
   let "jwat=${NRES}+${nwat_tot}"
   SELECTED_WATER=",${iwat}-${jwat}"
   cat active.pdb frozen.pdb > cmplxwat.pdb

fi
NEW_CMPLX_MASK="${CMPLX_MASK}${SELECTED_WATER}"

# Preparing CRD files
$PDBCRD  < cmplxwat.pdb > cmplxwat.crd

# Sander relaxation (everything moves, except water)
sed "s/DUMMY_MASK/\" ${NEW_CMPLX_MASK} \"/" sander_min.inp > sander_min_cmplxwat.inp 
$SANDER -O -i sander_min_cmplxwat.inp -p cmplxwat.top -c cmplxwat.crd -o cmplxwat.out_min -r cmplxwat.rst 

$CPPTRAJ  cmplxwat.top <<EOF
trajin cmplxwat.rst
trajout cmplxwat.pdb pdb  include_ep
go
EOF

# ascii (not formatted) xyz file for NMODE must be generated.
# this operation maximizes the number of significant digits in the
# optimized coordinates 
$NCDUMP cmplxwat.rst > temp.xyz
sed -i "1,/coordinates =/d" temp.xyz 
sed -i '$d' temp.xyz

echo $(cat temp.xyz | wc -l) > cmplxwat.xyz
echo "TCNG Optimized Structure " >> cmplxwat.xyz
cat temp.xyz >> cmplxwat.xyz

# NMODE calculations 
cat nmode.inp > nmode_cmplxwat.inp
echo ' ' >> nmode_cmplxwat.inp
$AMBMASK -p cmplxwat.top -out amber -c cmplxwat.crd -prnlev 0 -find "${NEW_CMPLX_MASK}"  | grep 'RES \|ATOM ' >> nmode_cmplxwat.inp
echo 'END' >> nmode_cmplxwat.inp
echo 'END' >> nmode_cmplxwat.inp
$NMODE -O -i nmode_cmplxwat.inp -p cmplxwat.top -c cmplxwat.xyz -o cmplxwat.nmode

mv cmplxwat.out_min $WORKDIR/${i/pdb/out_min}
mv cmplxwat.pdb     $WORKDIR/${i/pdb/pdb_min}
mv cmplxwat.nmode   $WORKDIR/${i/pdb/nmode}
gzip -f  $WORKDIR/${i/pdb/pdb_min} $WORKDIR/${i/pdb/nmode}   $WORKDIR/${i/pdb/out_min}

if [ "$NFRAG" -gt 1 ] 
then

    for ((ifrag=1;ifrag<=NFRAG;ifrag++))
    do

    let "iout = $ifrag + 3  "
    ext=nmode${iout}

    cat nmode.inp > nmode_cmplxwat.inp
    echo ' ' >> nmode_cmplxwat.inp
    $AMBMASK -p cmplxwat.top -out amber -c cmplxwat.crd -prnlev 0 -find ${NEW_FRAG_MASK["$ifrag"]}  | grep 'RES \|ATOM ' >> nmode_cmplxwat.inp
    echo 'END' >> nmode_cmplxwat.inp
    echo 'END' >> nmode_cmplxwat.inp
    $NMODE -O -i nmode_cmplxwat.inp -p cmplxwat.top -c cmplxwat.xyz -o cmplxwat.nmode
    mv cmplxwat.nmode   $WORKDIR/${i/.pdb/}.${ext}
    gzip -f $WORKDIR/${i/.pdb/}.${ext} 

    done 

fi

else 

  echo "Output files for ${i} are located in $WORKDIR."
  echo "Remove them if you wish to recompute this PDB snapshot ."

fi

done 
#=======================================================================================
 
#Cleaning up everything in the scratch directory
rm -r -f $TMPDIR 


